server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Remove H2 Console Configs

# JWT configurations (Secret should be at least 256-bit hex encoded)
todo.jwt.secret=${TODO_JWT_SECRET}
todo.jwt.expiration-ms=3600000
todo.jwt.refresh-expiration-ms=86400000

# OpenAPI/Swagger settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
spring.datasource.hikari.max-lifetime=600000
todo.google.client-id=${GOOGLE_CLIENT_ID}
todo.google.client-secret=${GOOGLE_CLIENT_SECRET}
todo.linkedin.session-cookie=${LINKEDIN_SESSION_COOKIE}
todo.instagram.session-cookie=${INSTAGRAM_SESSION_COOKIE}
spring.profiles.include=local
app.frontend.url=${FRONTEND_URL}
