server.port=8080

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=JExG9WZXgmGv2Sv.root
spring.datasource.password=U7MUd37GPeYQyA9Z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Remove H2 Console Configs

# JWT configurations (Secret should be at least 256-bit hex encoded)
todo.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
todo.jwt.expiration-ms=3600000
todo.jwt.refresh-expiration-ms=86400000

# OpenAPI/Swagger settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
